class catch_errors_from_log():
    def __init__():
        pass